fix: change expect
hexlet-basics/exercises-html pull request #166
Opened 2022-07-21 06:22 UTC by alvltab

change expect from 2 inputs to 3 options as in lesson's instructions

2022-07-25 11:54 UTC, dzencot commented
тест не проходит

2022-08-01 07:51 UTC, dzencot requested changes

2022-08-01 07:51 UTC, dzencot commented on modules/50-form/70-button/test.js
> +  expect(options).to.have.length(3);
Тут изменено поведение теста. Это точно нужно? Опишите пожалуйста какую проблему это решает? Пока не очень понятно для чего убраны проверки инпутов и изменено количество в проверке

2022-08-01 07:52 UTC, dzencot commented on modules/50-form/70-button/test.js
> +  expect(options).to.have.length(3);
@alvltab пишите, если нужна помощь по пулреквесту

2022-08-09 09:38 UTC, Malcom1986 commented on modules/50-form/70-button/test.js
> +  expect(options).to.have.length(3);
@alvltab Приветствую! Как дела пулреквестом? Нужна какая-то помощь?

2022-08-16 08:37 UTC, closed without merging